print "<div id='container'>"
print "<div id='header'>"
print "<br>"
print "<center><font color=white><h1>HELP CENTER</h1></font></center>"
print "</div>"
print "<div id='menubar'>"
##print "<table width='100%' border=0 id=menutable><tr><td align=center><a href='index.py'>Home</a></td>"
##print "<td align=center><a href='aboutus.py'>About Us</a></td>"
##print "<td align=center><a href='services.py'>Services</a></td>"
##print "<td align=center><a href='galler.py'>Gallery</a></td>"
##print "<td align=center><a href='contactus.py'>Contact Us</a></td>"
##print  "</tr>"
##print "</table>"
print "<ul><li><a href='index.py'>Home</a></li>"
print "<li><a href='aboutus.py'>About Us</a></li>"
print "<li class='dropdown'>"
print "<a href='javascript:void(0)' class='drpbtn'>Services</a>"
print "<div class='dropdown-content'>"
print "<a href='webdesign.py'>Web Design</a>"
print "<a href='webdevelopment.py'>Web Development</a>"
print "</div></li>"
print "<li><a href='gallery.py'>Gallery</a></li>"
print "<li><a href='contactus.py'>Contact Us</a></li>"
print "</ul>"
print "</div>"
print "<div id='leftpane'>"
print "<br><br><center>"
print "<iframe width='300' height='200' src='https://www.youtube.com/embed/zuxzE7--RYM' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen>"
print "</iframe></center>"
print "</div>"
print "<div id='rightpane'>"
print "<br><center>"
print """<iframe class='width-100 height-100'
src='https://www.google.com/maps/
embed?pb=!1m23!1m12!1m3!1d125320.92902620269!2d76.89690043863573!3d11.017678969269646!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x3ba85855b38e9b1d%3A0x1f3615975ec8f800!2slive+stream+technologies!3m2!1d11.017686999999999!2d76.96694099999999!5e0!3m2!1sen!2sin!4v1538080563075' width='400' height='250' frameborder='0' style='border:0' allowfullscreen>"
</iframe></center>"""
print "</div>"
print "<div id='footer'>"
print "<br>"
print "<center> <font color=white>&copy;Reserved to Company</font></center>"
print "</div>"
print "</div>"
