print "<div id='container'>"
print "<div id='header'>"
print "<br>"
print "<center><font color=white><h1>RECOVER PASSWORD</h1></font></center>"
print "</div>"
print "<div id='menubar'>"
##print "<table width='100%' border=0 id=menutable><tr><td align=center><a href='index.py'>Home</a></td>"
##print "<td align=center><a href='aboutus.py'>About Us</a></td>"
##print "<td align=center><a href='services.py'>Services</a></td>"
##print "<td align=center><a href='galler.py'>Gallery</a></td>"
##print "<td align=center><a href='contactus.py'>Contact Us</a></td>"
##print  "</tr>"
##print "</table>"
print "<ul><li><a href='index.py'>Home</a></li>"
print "<li><a href='aboutus.py'>About Us</a></li>"
print "<li class='dropdown'>"
print "<a href='javascript:void(0)' class='drpbtn'>Services</a>"
print "<div class='dropdown-content'>"
print "<a href='webdesign.py'>Web Design</a>"
print "<a href='webdevelopment.py'>Web Development</a>"
print "</div></li>"
print "<li><a href='gallery.py'>Gallery</a></li>"
print "<li><a href='contactus.py'>Contact Us</a></li>"
print "</ul>"
print "</div>"
print "<div id='commonpane'>"
print "<br><br><br>"
print "<table width='60%' height='40%' align=center border=0>"
print "<tr><td align=center>Recover Password</td></tr>"
print "<tr><td align=center><input type='text' name='uemail' placeholder='Enter Mobile / Email' required></td></tr>"
print "<tr><td align=center><input type='submit' name='fbutton'value='Retrieve'></td></tr>"
print "</table>"
print "</div>"
print "<div id='footer'>"
print "<br>"
print "<center> <font color=white>&copy;Reserved to Company</font></center>"
print "</div>"
print "</div>"
